// 新地域（京都・神奈川/横浜・福岡）の固有制度14件を追加（一回限り）。検証は data/verified_regions2_2026-07-17.md。
import { readFileSync, writeFileSync } from 'node:fs';
import { dirname, join } from 'node:path';
import { fileURLToPath } from 'node:url';
const ROOT = dirname(fileURLToPath(import.meta.url));
const path = join(ROOT, 'data/programs.data.json');
const programs = JSON.parse(readFileSync(path, 'utf8'));
const ALL = ['舞台', '音楽', '美術', '映像', '文芸・伝統芸能'];

const add = [
  // 京都
  { id: 'kyoto_shorei', name: '京都市芸術文化特別奨励制度', funder: '京都市', region: '京都府京都市', deadline: '2026-08-28（令和9年度・募集中）', dlUrgent: true, amount: '1個人／1グループ 300万円（採択2名）', payment: '奨励者決定後に交付（活動前に交付される奨励金型）', cashflow: '前払い型（活動前交付）', src: 'https://www.city.kyoto.lg.jp/bunshi/page/0000316361.html', note: '全ジャンル・ジャンル横断も可。京都市芸術新人賞受賞者等は対象外。', funderQ: '', conditions: ['個人（1名）またはグループ（2名以上）', '京都市内に住所地・活動拠点・発表場所のいずれか', '京都の芸術文化の振興・発信に貢献しうる活動', '1次書類・2次プレゼン審査'], genres: ALL },
  { id: 'arts_aid_kyoto', name: 'Arts Aid KYOTO 通常支援型', funder: '京都市', region: '京都府京都市', deadline: '2027年度分は例年5〜6月（2026年度分は終了）', dlUrgent: false, amount: '一般A 上限100万／一般B 上限20万／若手交流 上限10万', payment: '一般枠は概算払（前払い）可。若手交流枠は後払い精算', cashflow: '一般枠は前払い可／若手枠は後払い', src: 'https://www.city.kyoto.lg.jp/bunshi/page/0000302083.html', note: '通算3回以上採択済みの事業は対象外。寄付金等が財源。', funderQ: '', conditions: ['個人・団体・法人いずれも可', '京都市内に住所地・団体所在地・活動拠点のいずれか', '文化芸術事業の実施経験がある者', 'リアル公開を伴う公演・展示・リサーチ・WS等'], genres: ALL },
  { id: 'kac_coprogram', name: '京都芸術センター Co-program', funder: '京都市芸術文化協会（京都芸術センター）', region: '京都府京都市', deadline: '2027年度分は例年10月（2026年度分は終了）', dlUrgent: false, amount: 'A・B 各100万／C 30万（制作費上限）', payment: '未確認（会場・機材・制作室の現物提供が主）', cashflow: '未確認（現物提供中心）', src: 'https://www.kac.or.jp/open_call/', note: 'A=舞台芸術／B=展覧会（美術・映像・工芸等）／C=リサーチ・トーク・WS。京都在住要件の明記なし。', funderQ: '', conditions: ['個人・団体いずれも可', '京都芸術センターとの協働事業であること', '次世代アーティスト・芸術団体・キュレーター・研究者等'], genres: ALL },
  { id: 'kippu', name: 'U35創造支援プログラム KIPPU', funder: '京都芸術センター×ロームシアター京都×京都市', region: '京都府京都市', deadline: '2026-08-21（2027年度・募集中）', dlUrgent: true, amount: '現物支援（制作室・会場費・設備等。現金給付なし）', payment: '該当なし（現物支援）', cashflow: '現物支援（現金なし）', src: 'https://www.kac.or.jp/program/260621/', note: '舞台芸術（演劇・ダンス・音楽・伝統芸能）。居住地は問わないが京都で創作・上演する意欲が要件。', funderQ: '', conditions: ['個人または団体（代表/主たるアーティストが概ね35歳以下）', '過去3作品以上の上演経験', '京都で創作・上演する意欲'], genres: ['舞台', '音楽', '文芸・伝統芸能'] },
  { id: 'rohm_research', name: 'ロームシアター京都 リサーチプログラム', funder: '京都市音楽芸術文化振興財団（ロームシアター京都）', region: '京都府京都市', deadline: '例年4月（2026年度分は終了）', dlUrgent: false, amount: '調査研究補助費（2026年度は18万円と告知・一部未確認）', payment: '未確認', cashflow: '未確認', src: 'https://rohmtheatrekyoto.jp/join/', note: '舞台芸術・劇場文化に関するリサーチ。', funderQ: '', conditions: ['個人（リサーチャー）', '舞台芸術・劇場文化に関する調査研究の意欲', 'テーマ設定（伝統芸能等）または自己設定テーマ'], genres: ['舞台'] },
  { id: 'kyoto_challenge', name: '京都府文化力チャレンジ補助金', funder: '京都府', region: '京都府', deadline: '例年4〜5月（令和8年度分は終了）', dlUrgent: false, amount: '上限20万円（補助率2/3以内・京都市内は1/2以内）', payment: '未確認', cashflow: '未確認', src: 'https://www.pref.kyoto.jp/bungei/chalenge/r08/r8_challangeyoko.html', note: '個人向けの京都府独自の現金助成は確認できず（府は団体事業補助が中心）。', funderQ: '', conditions: ['団体のみ（個人不可・法人格不問・任意団体可）', '本拠が京都府内', '府内で実施（オンライン発信のみは対象外）', '子ども・青少年対象や地域文化資源の発信等の非営利文化事業'], genres: ALL },
  // 神奈川・横浜
  { id: 'acy_fellowship', name: 'つながる創造：ACYアーティスト・フェローシップ助成', funder: 'アーツコミッション・ヨコハマ（横浜市芸術文化振興財団）', region: '神奈川県横浜市', deadline: '例年2月頃（2026-2027年度分は終了）', dlUrgent: false, amount: '1年目100万＋2年目100万＝計200万円（定額）', payment: '未確認', cashflow: '未確認', src: 'https://acy.yafjp.org/grants/', note: 'ACY助成の採択歴がないことが条件。活動期間中に横浜市内拠点での滞在（最短6泊7日）が必要。', funderQ: '', conditions: ['美術・舞台芸術で活動するアーティスト個人（団体不可）', 'ACY助成の採択歴がないこと', '横浜市内拠点での滞在・地域住民との交流活動'], genres: ['舞台', '美術'] },
  { id: 'kanagawa_dantai', name: '神奈川県文化芸術活動団体事業補助金', funder: '神奈川県', region: '神奈川県', deadline: '例年2〜3月（令和8年度分は終了）', dlUrgent: false, amount: '上限100万円（補助率1/3以内・対象経費30万円未満は対象外）', payment: '精算払（後払い）', cashflow: '後払い（立替必須）', src: 'https://www.pref.kanagawa.jp/docs/yi4/hojyokin/bunkabosyu.html', note: '伝統芸能・青少年・高齢者・障がい者活動を優先枠。', funderQ: '', conditions: ['団体のみ（個人不可・任意団体可）', '県内に住所又は活動の本拠', '県内実施・広く県民対象の公演/展示/WS等', '営利団体・宗教政治目的は対象外'], genres: ALL },
  { id: 'kanagawa_magcul', name: '神奈川県マグカル展開促進補助金', funder: '神奈川県', region: '神奈川県', deadline: '年複数回（令和8年度後期は終了）', dlUrgent: false, amount: '通常1/3・上限100万／重点枠は1/2〜2/3・上限300〜1,000万', payment: '概算払（決定額100万超の事業のみ）＋精算払', cashflow: '後払い（100万超は概算払可）', src: 'https://www.pref.kanagawa.jp/docs/yi4/hojyokin/magculboshu.html', note: '重点枠=共生社会/地域活性化/伝統芸能/若年者育成。団体事業補助金との同時申請不可。', funderQ: '', conditions: ['民間団体（任意団体含む・個人は対象外）', '県内で実施し不特定多数に公開する「新たな」文化芸術事業'], genres: ALL },
  // 福岡
  { id: 'ffac_stepup', name: 'FFACステップアップ助成プログラム', funder: '福岡市文化芸術振興財団（アーツカウンシル福岡）', region: '福岡県福岡市', deadline: '例年4〜5月（令和8年度分は終了）', dlUrgent: false, amount: '普及活動 上限10万／発展活動 上限40万（令和7年度実績）', payment: '未確認', cashflow: '未確認', src: 'https://www.ffac.or.jp/projects/step-up/', note: '全ジャンル。専門アドバイザーの助言・フォローアップ付き。', funderQ: '', conditions: ['個人・団体いずれも可', '主に福岡市内で活動し今後の発展が期待される主催・実施活動'], genres: ALL },
  { id: 'ffac_kansho', name: 'FFAC文化芸術鑑賞サポート助成', funder: '福岡市文化芸術振興財団', region: '福岡県福岡市', deadline: '例年4月（令和8年度分は終了）', dlUrgent: false, amount: '未確認', payment: '未確認', cashflow: '未確認', src: 'https://www.ffac.or.jp/projects/kansyou/', note: '字幕・手話通訳・音声ガイド等の鑑賞サポートを行う取組が対象。', funderQ: '', conditions: ['市内で文化芸術活動を行う団体・法人', '字幕・手話・音声ガイド等でアクセシビリティを付加する取組'], genres: ALL },
  { id: 'fukuoka_bunka', name: '福岡文化財団 助成事業', funder: '公益財団法人 福岡文化財団', region: '福岡県', deadline: '随時受付（次の締切目安は8/15）', dlUrgent: true, amount: '上限30万円/1事業', payment: '未確認', cashflow: '未確認', src: 'https://ncfoundation.or.jp/bunka-zaidan/promotion/index.html', note: '審査は年2回（目安3月・9月／締切目安2月15日・8月15日）。', funderQ: '', conditions: ['福岡県内で芸術文化活動を行う法人及び団体（個人単独は不可）', '自ら企画・主催し実現性のある事業', '過去3年連続助成を受けていないこと'], genres: ['舞台', '音楽', '美術'] },
  { id: 'kitakyushu_tryarts', name: '北九州市 文化芸術次世代育成事業 TRY ARTs', funder: '北九州市芸術文化振興財団（KICPAC）', region: '福岡県北九州市', deadline: '例年4〜5月（令和8年度分は終了）', dlUrgent: false, amount: '上限100万円（補助率1/2以内）', payment: '未確認', cashflow: '未確認', src: 'https://www.kicpac.org/subsidy/try-arts2026.html', note: '実演芸術＋視覚芸術（美術・写真・映画・デザイン・メディアアート）。', funderQ: '', conditions: ['個人・団体いずれも可', '北九州市内に住所または活動拠点', '市内を主会場に一般公開される上演・展示等', '例年同様・新たな試みがない企画は不採択の場合あり'], genres: ALL },
  { id: 'fcif', name: '福岡よかトピア国際交流財団 国際交流活動助成事業', funder: '福岡よかトピア国際交流財団（FCIF）', region: '福岡県福岡市', deadline: '2026-08-07（募集中）', dlUrgent: true, amount: '講演会等 上限10万／その他 上限20万（補助率5割以内）', payment: '精算払（事業完了後2か月以内に実績報告→交付）', cashflow: '後払い（立替必須）', src: 'https://www.fcif.or.jp/money/subsidy/', note: '★国際交流・国際理解の要素が必須（純粋な芸術のみは対象可否を要問い合わせ）。', funderQ: '', conditions: ['個人・団体いずれも可', '福岡都市圏に活動基盤があり福岡市民の国際交流に資する', '国際交流・国際理解・多文化共生に寄与する事業', '営利・宗教・政治目的は対象外'], genres: ALL },
];

const ids = new Set(programs.map((p) => p.id));
let added = 0;
for (const p of add) if (!ids.has(p.id)) { programs.push(p); added++; }
writeFileSync(path, JSON.stringify(programs) + '\n');
console.log(`added ${added}. total=${programs.length}`);
