// 美術・映像・文芸/伝統芸能の特化19制度を追加（一回限り）。一次検証は data/verified_genres_2026-07-17.md 参照。
import { readFileSync, writeFileSync } from 'node:fs';
import { dirname, join } from 'node:path';
import { fileURLToPath } from 'node:url';
const ROOT = dirname(fileURLToPath(import.meta.url));
const path = join(ROOT, 'data/programs.data.json');
const programs = JSON.parse(readFileSync(path, 'utf8'));

const add = [
  // 映像
  { id: 'eiga_seisaku', name: '日本映画製作支援事業', funder: '文化庁／日本芸術文化振興会', region: '全国', deadline: '令和8年度分終了（年2回・次回は令和9年度分）', dlUrgent: false, amount: '劇映画 上限535〜2,140万／記録214〜1,605万／アニメ107〜2,140万', payment: '精算払（後払い）。制作費は自己資金で立替が前提', cashflow: '後払いのみ（立替必須）', src: 'https://www.bunka.go.jp/seisaku/geijutsubunka/eiga/seisaku_shien/', note: 'テレビ用作品は対象外。バリアフリー字幕・音声ガイド費を別途上限100万×2計上可。', funderQ: '', conditions: ['映画製作を主目的とする法人格ある日本の団体（個人・製作委員会名義は不可）', '過去に映画を製作し一般公開した実績が必要', '著作権の全部又は一部を保有', '劇映画・記録映画・アニメーション映画の日本映画'], genres: ['映像'] },
  { id: 'mediaarts_creator', name: '文化庁 メディア芸術クリエイター育成支援事業', funder: '文化庁（CG-ARTS）', region: '全国', deadline: '令和8年度分終了（次回は令和9年度分）', dlUrgent: false, amount: '創作支援 最大500万／発表支援 最大100万', payment: '未確認', cashflow: '未確認', src: 'https://creators.j-mediaarts.bunka.go.jp/', note: '対象はメディア芸術（アニメ/メディアアート/ゲーム/マンガ）。実写の劇映画・ドキュメンタリーは対象外。', funderQ: '', conditions: ['個人・団体いずれも応募可（法人格不要）', '創作支援=活動歴5年以上or受賞歴のある概ね40代までのクリエイター', '発表支援=活動歴3年以上のクリエイター/団体', '短編アニメ・メディアアート等の制作費に充当可'], genres: ['映像', '美術'] },
  { id: 'kikin_bijutsu', name: '芸術文化振興基金 美術・メディア芸術等の創造普及活動', funder: '日本芸術文化振興会（基金）', region: '全国', deadline: '令和8年度分終了（次回は例年10月末〜11月）', dlUrgent: false, amount: '定額制4区分（50〜200万円）', payment: '精算払（後払い）', cashflow: '後払いのみ（立替必須）', src: 'https://www.ntj.jac.go.jp/grant/program/applicant/01/', note: '短編アニメ・実験映像も応募可（注釈で明記）。展示・上映を伴う創造普及活動が対象。', funderQ: '', conditions: ['芸術団体（個人不可・任意団体は可）', '美術・メディア芸術（漫画/アニメ/メディアアート等）の展示活動', '過去に国内で自ら主催した美術展示の実績', '作品を販売する活動・文化庁補助金が入る活動は対象外'], genres: ['美術', '映像'] },
  { id: 'kikin_eigasai', name: '芸術文化振興基金 国内映画祭等の活動', funder: '日本芸術文化振興会（基金）', region: '全国', deadline: '令和8年度分終了（次回は例年10月末〜11月）', dlUrgent: false, amount: '映画祭 上限500万／日本映画上映活動 上限100万', payment: '精算払（後払い）', cashflow: '後払いのみ（立替必須）', src: 'https://www.ntj.jac.go.jp/kikin/', note: '制作費でなく上映・映画祭の普及活動が対象。', funderQ: '', conditions: ['団体のみ（個人不可）', '映画祭を主催する日本の団体で過去に自ら主催した実績', '日本映画の上映・普及活動'], genres: ['映像'] },
  { id: 'kokusai_eiga', name: '国際共同製作映画支援事業', funder: '文化庁／日本芸術文化振興会', region: '全国／海外', deadline: '令和8年度分あり（時期は文化庁公募参照）', dlUrgent: false, amount: '補助率1/5以内・上限5,000万〜1億円', payment: '未確認', cashflow: '未確認', src: 'https://www.bunka.go.jp/shinsei_boshu/kobo/94137301.html', note: '補助対象経費1億円以上・上映1時間以上の大規模枠。', funderQ: '', conditions: ['映画製作を主目的とする日本の団体で一般公開映画の製作実績', '国際共同製作の劇映画・アニメーション映画', '大規模枠のため個人・小団体は対象外'], genres: ['映像'] },
  // 美術
  { id: 'pola_zaigai', name: 'ポーラ美術振興財団 若手芸術家の在外研修助成', funder: 'ポーラ美術振興財団', region: '全国／海外', deadline: '例年10〜11月（令和8年度分は終了）', dlUrgent: false, amount: '1名12か月360万円以内（保存修復は2年720万）', payment: '未確認', cashflow: '未確認', src: 'https://www.pola-art-foundation.jp/', note: '絵画・彫刻・工芸等の創作、または展覧会企画・保存修復・教育普及。', funderQ: '', conditions: ['個人のみ', '2026/4/1時点で20歳以上40歳未満・日本国籍か永住資格', '海外での研修（受入保証が必要）', '研修中は常勤職に就かない'], genres: ['美術'] },
  { id: 'pola_kokusai', name: 'ポーラ美術振興財団 美術に関する国際交流助成', funder: 'ポーラ美術振興財団', region: '全国／海外', deadline: '例年10〜11月（2026年度分は終了）', dlUrgent: false, amount: '1件200万円以内', payment: '未確認', cashflow: '未確認', src: 'https://www.pola-art-foundation.jp/', note: '', funderQ: '', conditions: ['個人・NPO・任意団体など可', '日本の美術家の海外個展・共同展／海外美術館との共同展、または外国人美術家が参加する国内の国際交流', '実績要件なし'], genres: ['美術'] },
  { id: 'nomura_art', name: '野村財団 芸術・文化助成（美術部門・個人活動助成金）', funder: '野村財団', region: '全国', deadline: '例年4月（2026年度分は終了）', dlUrgent: false, amount: '上限100万円', payment: '未確認', cashflow: '未確認', src: 'https://www.nomurafoundation.or.jp/culture/art.html', note: 'ほかに個人奨学助成金・団体活動助成金も。', funderQ: '', conditions: ['個人（本人のみで使用）', '展覧会出品・個展・アーティスト・イン・レジデンス参加', '美術の分野'], genres: ['美術'] },
  { id: 'ogasawara', name: '小笠原敏晶記念財団 文化・芸術助成（現代美術・調査研究等）', funder: '小笠原敏晶記念財団', region: '全国', deadline: '2026-09-17（調査研究・受付中）', dlUrgent: true, amount: '調査研究 1件30〜300万円（総額7,000万予定）', payment: '未確認', cashflow: '未確認', src: 'https://ogasawarazaidan.or.jp/artculture/', note: '調査研究のほか交流/渡航/翻訳/特定課題の枠も。制作より調査・研究寄り。', funderQ: '', conditions: ['個人・団体・法人格いずれも可', '現代美術史・キュレーション・保存修復・教育普及、創作に係る調査研究', '成果発表・成果物作成費も対象（学術論文執筆は対象外）'], genres: ['美術'] },
  { id: 'dnp', name: 'DNP文化振興財団 グラフィック文化に関する学術研究助成', funder: 'DNP文化振興財団', region: '全国', deadline: '例年4〜6月（2026年度分は終了）', dlUrgent: false, amount: '1件 上限50万円/年（最長2年）', payment: '未確認', cashflow: '未確認', src: 'https://www.dnpfcp.jp/foundation/grants/', note: '制作でなく学術研究が対象。', funderQ: '', conditions: ['個人研究者も応募可', 'グラフィックデザイン/グラフィックアート・アーカイブ研究', '全国応募可'], genres: ['美術'] },
  { id: 'kao_bijutsu', name: '花王芸術・科学財団 美術展覧会への助成', funder: '花王芸術・科学財団', region: '全国', deadline: '例年10〜11月（2026年度分は終了）', dlUrgent: false, amount: '1件 上限100万円', payment: '前払い（開催月初めに銀行振込・団体口座必須）', cashflow: '開催時交付（実質前払い）', src: 'https://www.kao-foundation.or.jp/art/art_exhibition/', note: '個人アーティストの制作費・管理運営費は対象外。2年連続不可。', funderQ: '', conditions: ['日本の美術館・博物館もしくは団体が企画・開催', '絵画・版画・彫刻等の展覧会', '個人の制作活動費は対象外（団体口座必須）'], genres: ['美術'] },
  { id: 'kao_mediaart', name: '花王芸術・科学財団 メディアアートへの助成', funder: '花王芸術・科学財団', region: '全国', deadline: '例年10〜11月（2026年度分は終了）', dlUrgent: false, amount: '1件 上限100万円', payment: '前払い（開催3か月前の月初に振込・団体口座必須）', cashflow: '開催前交付（実質前払い）', src: 'https://www.kao-foundation.or.jp/art/mediaart/', note: '対面開催必須（オンライン限定不可）。個人名義受給は不可。', funderQ: '', conditions: ['国内で企画された展覧会・プロジェクト・パフォーマンス等', 'デジタル技術を核とする作品', '団体口座必須（個人名義不可）'], genres: ['美術', '映像'] },
  { id: 'takashimaya', name: '公益信託タカシマヤ文化基金 団体助成', funder: 'タカシマヤ文化基金', region: '全国', deadline: '年1回（要最新確認）', dlUrgent: false, amount: '総額200万円以内（1〜2団体へ配分）', payment: '未確認', cashflow: '未確認', src: 'https://www.zenbi.jp/', note: '別枠「タカシマヤ美術賞」は推薦型で自己応募不可。', funderQ: '', conditions: ['団体のみ（個人不可）', '国際文化交流のシンポジウム、または美術文化の保存・発掘・振興で実績ある団体'], genres: ['美術'] },
  { id: 'togei_shien', name: '現代美術文化振興財団 陶芸家支援助成金', funder: '現代美術文化振興財団', region: '全国', deadline: '例年春（第15期は2026-06-05終了）', dlUrgent: false, amount: '月額3万円（年額36万円・給付型）', payment: '6か月ごとに本人口座へ振込（分割）', cashflow: '分割前払い型', src: 'https://modernart-foundation.com/', note: '募集10名以内。累計3回まで再応募可。', funderQ: '', conditions: ['個人のみ', '陶芸（陶磁土を用いた立体造形）限定', '学校・師の推薦、または独自の創作活動'], genres: ['美術', '文芸・伝統芸能'] },
  // 文芸・伝統芸能
  { id: 'matsuo', name: '松尾芸能振興財団 助成事業', funder: '松尾芸能振興財団', region: '全国', deadline: '例年6月（2026年度分は終了）', dlUrgent: false, amount: '上限100万円', payment: '助成決定後に相談のうえ交付（方式は未確認）', cashflow: '未確認', src: 'https://matsuo.or.jp/', note: '伝統芸能活動・工芸技術継承・地域芸能振興・伝統芸能教育の4区分。', funderQ: '', conditions: ['個人・団体いずれも可', '伝統芸能の継承・普及・創作、または工芸技術継承', '過去の活動が分かる資料の提出必須', '出演料・報酬等の人件費、コンクール主体の事業は対象外'], genres: ['文芸・伝統芸能'] },
  { id: 'mutfa_chiiki', name: '三菱UFJ信託地域文化財団 助成事業', funder: '三菱UFJ信託地域文化財団', region: '全国', deadline: '例年8〜11月（2026年度分は終了）', dlUrgent: false, amount: '近年実績1件20〜70万円程度', payment: '未確認', cashflow: '未確認', src: 'https://www.bunka.go.jp/seisaku/geijutsubunka/mecenat/shien/zaidan/1420943.html', note: '音楽・美術・演劇・伝統芸能の4部門（アマチュアの団体・公演に限る）。「芸術文化財団」とは別法人。', funderQ: '', conditions: ['団体のみ（個人不可・法人格不要・アマチュア）', '伝統芸能祭・舞踊・能・人形浄瑠璃・神楽等の保存伝承・後継者育成の公演', '国内の地域文化振興に寄与する公演'], genres: ['文芸・伝統芸能'] },
  { id: 'kikin_dento', name: '芸術文化振興基金 伝統芸能・大衆芸能の公開活動', funder: '日本芸術文化振興会（基金）', region: '全国', deadline: '令和8年度分終了（次回は例年10月末〜11月）', dlUrgent: false, amount: '区分・活動規模により算定', payment: '精算払（後払い）が原則', cashflow: '後払い（概算払は要件次第）', src: 'https://www.ntj.jac.go.jp/kikin/', note: '伝統芸能（文楽・歌舞伎・能楽・邦楽・邦舞等）／大衆芸能（落語・講談・浪曲・漫才等）。', funderQ: '', conditions: ['団体（個人不可・任意団体は可）', '伝統芸能の公開活動 or 大衆芸能の公演', '保存・普及を主目的とする我が国の団体'], genres: ['文芸・伝統芸能'] },
  { id: 'pola_dento', name: 'ポーラ伝統文化振興財団 助成事業', funder: 'ポーラ伝統文化振興財団', region: '全国', deadline: '例年2〜3月（次回具体日は要確認）', dlUrgent: false, amount: '1件概ね30〜200万円（複数年事業は最長約3年）', payment: '未確認', cashflow: '未確認', src: 'https://www.polaculture.or.jp/', note: '伝統工芸・伝統芸能・民俗芸能/行事の保存・向上。1個人・1団体1件。', funderQ: '', conditions: ['個人・団体いずれも可（法人格不要・原則恒常的活動体）', '無形の伝統文化の保存記録・後継者育成・普及・調査研究・技術伝承'], genres: ['文芸・伝統芸能'] },
  { id: 'sato_kogei', name: '美術工芸振興佐藤基金 研究助成', funder: '美術工芸振興佐藤基金', region: '全国', deadline: '2026-09-18（受付中の可能性・要確認）', dlUrgent: true, amount: '1件 上限約70万円（総額350万・5件程度）', payment: '未確認', cashflow: '未確認', src: 'https://www.jfc.or.jp/subsidy/grants230621-001/', note: '陶芸・ガラス・金工・石工・木工・漆芸・染織等の工芸。', funderQ: '', conditions: ['個人・団体いずれも可', '工芸の研究・創作・調査・成果発表・教育普及', '計画遂行能力と実績を持つ日本の研究者/創作者'], genres: ['美術', '文芸・伝統芸能'] },
];

const ids = new Set(programs.map((p) => p.id));
let added = 0;
for (const p of add) if (!ids.has(p.id)) { programs.push(p); added++; }
writeFileSync(path, JSON.stringify(programs) + '\n');
const c = (t) => programs.filter((p) => (p.genres || []).includes(t)).length;
console.log(`added ${added}. total=${programs.length} / 舞台=${c('舞台')} 音楽=${c('音楽')} 美術=${c('美術')} 映像=${c('映像')} 文芸伝統=${c('文芸・伝統芸能')}`);
